### ISSUE TITLE
Unclosed httpx.AsyncClient warning

### ISSUE THREAD

**Issue by jeanmonet** [bibajz/bitcoin-python-async-rpc#6]
Hi - thank you for this great (and light) library!

Upon exiting the script, I often get the following warning:

```
/lib/python3.9/site-packages/httpx/_client.py:1781: UserWarning: Unclosed <httpx.AsyncClient object at 0x7ac57ff51310>.
See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
```

I'm not really familiar with the httpx library so not sure what this implies. Should the bitcoinrpc library provide a call to close the httpxAsyncClient?

**Comment by bibajz** [comment]
Hello, thank you for reporting the issue!

It was about time I looked on this library again, possibly adding some new features, since bitcoin core 0.21 was released...

The warning you receive was introduced here: https://github.com/encode/httpx/pull/1197. I will take a closer look on it during this weekend a once again, thank you for reporting.

Libor

**Comment by feavilan04** [comment]
Hi there.

Thanks for the library. 

I'm using the library and getting the same error @jeanmonet  quote above.

Please help us to check it up.

**Comment by bibajz** [comment]
Hey guys, sorry for the late response, I was partly busy IRL and partly slacking... :D

Since I am not near the Bitcoin node I operate and therefore unable to query it, I looked around the interwebs for running `regtest` node without minimum hussle and found a [docker image](https://hub.docker.com/r/bitcoindevelopernetwork/bitcoind-regtest).

It is not up to date, running Bitcoin Core v0.17.1 but it is sufficient for now - This commit https://github.com/bibajz/bitcoin-python-async-rpc/commit/645c25d0c69c5004d1f36849aeffb9a4f8a2c01e adds a simple script for running regtest locally on port 18443 with `rpc_user/rpc_password` credentials.

This also opens a possibility for better testing, since I can setup/teardown the regtest container in an instant - stay tuned! :)

But, to your problem, I have confirmed it and had the same issue with this simple script run from CLI:

```
import asyncio

from bitcoinrpc import BitcoinRPC


async def main():
    c = BitcoinRPC("localhost", 18443, "rpc_user", "rpc_password")
    print(await c.getbestblockhash())

if __name__ == "__main__":
    asyncio.run(main())
```

To close the `httpx.AsyncClient`, I have pushed https://github.com/bibajz/bitcoin-python-async-rpc/commit/19aad69a31092b21a42d3fcc349b28405fc37c78, which adds a `BitcoinRPC.aclose` coroutine which can be called to close the client.

Slightly modified script from above:

```
import asyncio

from bitcoinrpc import BitcoinRPC


async def main():
    c = BitcoinRPC("localhost", 18443, "rpc_user", "rpc_password")
    print(await c.getbestblockhash())
    await c.aclose()

if __name__ == "__main__":
    asyncio.run(main())
```
no longer emits the warning.

However, remembering to `aclose` the client everytime feels repetitive and also can be forgotten - I am thinking about adding the possibility to use `BitcoinRPC` as an asynchronous context manager, so the closing would be managed automatically, like this:

```
async with BitcoinRPC(...) as client:
    ...
```

What do you think @feavilan04, @jeanmonet ? Anyway, I will push the new version of this package to PyPI in few days.

Thank you both for your feedback and I promise my responses will be faster next time!

Libor

**Comment by feavilan04** [comment]
Thanks a lot @bibajz for the library, the last approach seems perfect for the job, let me know if you need anything.

Regards.

**Comment by jeanmonet** [comment]
@bibajz 
> However, remembering to `aclose` the client everytime feels repetitive and also can be forgotten - I am thinking about adding the possibility to use `BitcoinRPC` as an asynchronous context manager, so the closing would be managed automatically, like this:
> 
> ```
> async with BitcoinRPC(...) as client:
>     ...
> ```

The first solution using explicit `.aclose()` was indeed necessary. Considering this new requirement, your idea to make an async context manager makes a lot of sense IMO. If it doesn't make things complicated, dunno if both possibilities should be allowed (context manager + existing api)? Thanks for maintaining!

**Comment by bibajz** [comment]
Hey @jeanmonet, indeed it was... :)

I have implemented async context manager today, pushing it soon. Both options, calling the `BitcoinRPC.aclose` coroutine as well as using the async context manager, will be possible.

**Comment by bibajz** [comment]
OK, new version - `v0.4.0` - is out! With `aclose` and async context manager - https://pypi.org/project/bitcoinrpc/0.4.0/

Thanks a lot! @jeanmonet @feavilan04

**Comment by jeanmonet** [comment]
> OK, new version - `v0.4.0` - is out! With `aclose` and async context manager - https://pypi.org/project/bitcoinrpc/0.4.0/
> 
> Thanks a lot! @jeanmonet @feavilan04

Awesome thanks!
